#!/bin/sh
# autotools makes such a mess.
#
for f in AUTHORS NEWS README ChangeLog; do
    [ -s "$f" ] || rm -f "$f"
done
rm -r -f autom4te.cache .deps src/.deps
rm -f `cat <<EOF
    INSTALL
    Makefile
    Makefile.in
    aclocal.m4
    config.log
    config.status
    configure
    depcomp
    install-sh
    missing
    src/Makefile
    src/Makefile.in
    src/*.o
    src/help.c
    src/qperf.1
    src/qperf
EOF`

if
    ! grep -q -s '^BuildRequires: *libibverbs-devel' qperf.spec ||
    [ qperf.spec.in -nt qperf.spec ] ||
    [ configure.in -nt qperf.spec ]
then
    rm -f qperf.spec
fi
